"""Add profession to person

Revision ID: 38a290864cee
Revises: 56a1c507ab7d
Create Date: 2026-07-02 01:42:05.645988+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a290864cee'
down_revision: Union[str, None] = '56a1c507ab7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('profession', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'profession')
    # ### end Alembic commands ###
